# Rewrite spiral.js clean from scratch
# Uses window.innerWidth/Height directly -- no DOM measurement needed

src = ""
src += "// Nimbis anchor: js/app/views/spiral.js\n"
src += "// SPIRALSIDE -- SPIRAL VIEW v2.0\n"
src += "\n"
src += "const SpiralView = (() => {\n"
src += "  const PRESETS = {\n"
src += "    sky:      { type:'log',    color:'#00F6D6', speed:0.6,  density:180, dir:1,  particles:true,  decay:false },\n"
src += "    cold:     { type:'archi',  color:'#4DA3FF', speed:0.3,  density:220, dir:-1, particles:false, decay:false },\n"
src += "    monday:   { type:'fib',    color:'#FF4BCB', speed:1.1,  density:140, dir:1,  particles:true,  decay:true  },\n"
src += "    grit:     { type:'galaxy', color:'#FFD93D', speed:0.5,  density:160, dir:1,  particles:true,  decay:false },\n"
src += "    architect:{ type:'archi',  color:'#F3F7FF', speed:0.25, density:260, dir:-1, particles:false, decay:false },\n"
src += "    custom:   { type:'log',    color:'#7c6af7', speed:0.6,  density:180, dir:1,  particles:true,  decay:false },\n"
src += "  };\n"
src += "  let canvas, ctx, animId, ptcls=[], angle=0;\n"
src += "  let idleTimer=null, ssActive=false, ssOverlay=null;\n"
src += "  const cfg={ type:'log',color:'#00F6D6',speed:0.6,density:180,dir:1,particles:true,decay:false,idleMins:5,activePreset:'sky' };\n"
src += "\n"
src += "  function archi(cx,cy,maxR,turns,th){\n"
src += "    const p=[],s=Math.round(cfg.density*turns),b=maxR/(turns*Math.PI*2);\n"
src += "    for(let i=0;i<=s;i++){const t=(i/s)*turns*Math.PI*2,a=t*cfg.dir+th;p.push([cx+b*t*Math.cos(a),cy+b*t*Math.sin(a)]);} return p;\n"
src += "  }\n"
src += "  function log_(cx,cy,maxR,turns,th){\n"
src += "    const p=[],s=Math.round(cfg.density*turns),b=Math.log(maxR)/(turns*Math.PI*2);\n"
src += "    for(let i=0;i<=s;i++){const t=(i/s)*turns*Math.PI*2,a=t*cfg.dir+th;p.push([cx+Math.exp(b*t)*Math.cos(a),cy+Math.exp(b*t)*Math.sin(a)]);} return p;\n"
src += "  }\n"
src += "  function fib(cx,cy,maxR,th){\n"
src += "    const p=[],n=cfg.density*3,g=Math.PI*(3-Math.sqrt(5));\n"
src += "    for(let i=0;i<n;i++){const r=maxR*Math.sqrt(i/n),a=i*g*cfg.dir+th;p.push([cx+r*Math.cos(a),cy+r*Math.sin(a)]);} return p;\n"
src += "  }\n"
src += "  function galaxy(cx,cy,maxR,turns,th){\n"
src += "    const p=[],arms=3,s=Math.round(cfg.density*turns),b=Math.log(maxR)/(turns*Math.PI*2);\n"
src += "    for(let arm=0;arm<arms;arm++){const off=(arm/arms)*Math.PI*2;\n"
src += "      for(let i=0;i<=s;i++){const t=(i/s)*turns*Math.PI*2,dr=0.18*Math.sin(t*1.4),a=(t+dr)*cfg.dir+th+off;p.push([cx+Math.exp(b*t)*Math.cos(a),cy+Math.exp(b*t)*Math.sin(a)]);}\n"
src += "    } return p;\n"
src += "  }\n"
src += "  function rgba(hex,alpha){const r=parseInt(hex.slice(1,3),16),g=parseInt(hex.slice(3,5),16),b=parseInt(hex.slice(5,7),16);return 'rgba('+r+','+g+','+b+','+alpha+')';}\n"
src += "\n"
src += "  function draw(){\n"
src += "    const W=canvas.width,H=canvas.height,cx=W/2,cy=H/2,maxR=Math.min(W,H)*0.44;\n"
src += "    if(cfg.decay){ctx.fillStyle='rgba(10,10,15,0.12)';ctx.fillRect(0,0,W,H);}else{ctx.clearRect(0,0,W,H);}\n"
src += "    let pts;\n"
src += "    if(cfg.type==='archi') pts=archi(cx,cy,maxR,5,angle);\n"
src += "    else if(cfg.type==='fib') pts=fib(cx,cy,maxR,angle);\n"
src += "    else if(cfg.type==='galaxy') pts=galaxy(cx,cy,maxR,4,angle);\n"
src += "    else pts=log_(cx,cy,maxR,5,angle);\n"
src += "    if(cfg.type==='fib'){\n"
src += "      pts.forEach(([x,y],i)=>{ctx.beginPath();ctx.arc(x,y,1.4,0,Math.PI*2);ctx.fillStyle=rgba(cfg.color,0.3+(i/pts.length)*0.7);ctx.fill();});\n"
src += "    }else{\n"
src += "      for(let i=1;i<pts.length;i++){ctx.beginPath();ctx.moveTo(pts[i-1][0],pts[i-1][1]);ctx.lineTo(pts[i][0],pts[i][1]);ctx.strokeStyle=rgba(cfg.color,0.12+(i/pts.length)*0.88);ctx.lineWidth=0.9+(i/pts.length)*0.6;ctx.stroke();}\n"
src += "    }\n"
src += "    if(cfg.particles&&pts.length>10){ptcls.forEach(p=>{const idx=Math.floor(p.pos*(pts.length-1));const[px,py]=pts[idx];ctx.beginPath();ctx.arc(px+p.ox,py+p.oy,p.r,0,Math.PI*2);ctx.fillStyle=rgba(cfg.color,p.alpha);ctx.fill();p.pos=(p.pos+p.spd)%1;p.ox+=(Math.random()-0.5)*0.3;p.ox*=0.92;p.oy+=(Math.random()-0.5)*0.3;p.oy*=0.92;});}\n"
src += "    angle+=0.004*cfg.speed*cfg.dir;\n"
src += "  }\n"
src += "  function initP(){ptcls=Array.from({length:28},(_,i)=>({pos:i/28,spd:0.0008+Math.random()*0.0012,r:1.2+Math.random()*2.2,alpha:0.4+Math.random()*0.55,ox:0,oy:0}));}\n"
src += "  function loop(){draw();animId=requestAnimationFrame(loop);}\n"
src += "  function stopLoop(){if(animId){cancelAnimationFrame(animId);animId=null;}}\n"
src += "  function setSize(){\n"
src += "    if(!canvas)return;\n"
src += "    // Use offsetWidth/Height of the view container directly\n"
src += "    const v=document.getElementById('view-spiral');\n"
src += "    canvas.width  = v ? v.offsetWidth  : window.innerWidth;\n"
src += "    canvas.height = v ? (v.offsetHeight - 220) : (window.innerHeight - 220);\n"
src += "    if(canvas.height<100) canvas.height = window.innerHeight - 220;\n"
src += "  }\n"
src += "\n"
src += "  function resetIdle(){clearTimeout(idleTimer);if(ssActive)exitSS();if(cfg.idleMins>0)idleTimer=setTimeout(enterSS,cfg.idleMins*60*1000);}\n"
src += "  function enterSS(){\n"
src += "    if(ssActive)return;ssActive=true;\n"
src += "    ssOverlay=document.createElement('div');ssOverlay.id='spiral-ss';\n"
src += "    ssOverlay.style.cssText='position:fixed;inset:0;z-index:8888;background:#0a0a0f;cursor:none;';\n"
src += "    const sc=document.createElement('canvas');sc.style.cssText='position:absolute;inset:0;width:100%;height:100%;';\n"
src += "    ssOverlay.appendChild(sc);\n"
src += "    const mk=document.createElement('div');mk.textContent='spiralside';\n"
src += "    mk.style.cssText='position:absolute;bottom:40px;left:50%;transform:translateX(-50%);font-family:Syne,sans-serif;font-size:0.75rem;letter-spacing:0.25em;color:rgba(243,247,255,0.08);pointer-events:none;';\n"
src += "    ssOverlay.appendChild(mk);document.body.appendChild(ssOverlay);\n"
src += "    ['click','touchstart','keydown','mousemove'].forEach(ev=>ssOverlay.addEventListener(ev,exitSS,{once:true}));\n"
src += "    ssOverlay._prev=canvas;canvas=sc;ctx=sc.getContext('2d');sc.width=window.innerWidth;sc.height=window.innerHeight;\n"
src += "  }\n"
src += "  function exitSS(){if(!ssActive||!ssOverlay)return;ssActive=false;if(ssOverlay._prev){canvas=ssOverlay._prev;ctx=canvas.getContext('2d');}ssOverlay.remove();ssOverlay=null;resetIdle();}\n"
src += "  function savePNG(){canvas.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='spiral-'+cfg.activePreset+'-'+Date.now()+'.png';a.click();});}\n"
src += "  function q(s){return document.querySelector(s);}\n"
src += "\n"
src += "  function applyPreset(name){\n"
src += "    const p=PRESETS[name]||PRESETS.custom;Object.assign(cfg,p);cfg.activePreset=name;initP();syncCtrl();\n"
src += "    document.querySelectorAll('.sp-preset').forEach(c=>c.classList.toggle('active',c.dataset.preset===name));\n"
src += "  }\n"
src += "  function syncCtrl(){\n"
src += "    const t=q('#sp-type');if(t)t.value=cfg.type;\n"
src += "    const c=q('#sp-color');if(c)c.value=cfg.color;\n"
src += "    const sw=q('#sp-cswatch');if(sw)sw.style.background=cfg.color;\n"
src += "    const sp=q('#sp-speed');if(sp)sp.value=cfg.speed*10;\n"
src += "    const sv=q('#sp-spval');if(sv)sv.textContent=cfg.speed.toFixed(1)+'x';\n"
src += "    const dn=q('#sp-density');if(dn)dn.value=cfg.density;\n"
src += "    const dv=q('#sp-dnval');if(dv)dv.textContent=cfg.density;\n"
src += "    const dr=q('#sp-dir');if(dr)dr.textContent=cfg.dir===1?'CW':'CCW';\n"
src += "    const pt=q('#sp-ptcl');if(pt)pt.classList.toggle('on',cfg.particles);\n"
src += "    const dc=q('#sp-decay');if(dc)dc.classList.toggle('on',cfg.decay);\n"
src += "  }\n"
src += "\n"
src += "  function injectCSS(){\n"
src += "    if(document.getElementById('spiral-css'))return;\n"
src += "    const s=document.createElement('style');s.id='spiral-css';\n"
src += "    s.textContent=[\n"
src += "      '#sp-wrap{display:flex;flex-direction:column;width:100%;height:100%;}',\n"
src += "      '#sp-presets{display:flex;gap:6px;padding:10px 14px 6px;overflow-x:auto;flex-shrink:0;scrollbar-width:none;}',\n"
src += "      '#sp-presets::-webkit-scrollbar{display:none;}',\n"
src += "      '.sp-preset{padding:5px 14px;border-radius:20px;border:1px solid var(--border,#1e1e2e);background:var(--surface,#111118);color:var(--subtext,#7070a0);font-family:var(--font-ui,monospace);font-size:0.65rem;letter-spacing:0.08em;cursor:pointer;white-space:nowrap;transition:all 0.2s;flex-shrink:0;}',\n"
src += "      '.sp-preset:hover,.sp-preset.active{border-color:#6af7c8;color:#6af7c8;}',\n"
src += "      '.sp-preset.active{background:rgba(106,247,200,0.08);}',\n"
src += "      '#sp-canvas{display:block;flex-shrink:0;}',\n"
src += "      '#sp-ctrl{flex-shrink:0;padding:10px 14px calc(10px + env(safe-area-inset-bottom,0px));border-top:1px solid var(--border,#1e1e2e);background:var(--surface,#111118);display:flex;flex-direction:column;gap:7px;}',\n"
src += "      '.sp-row{display:flex;align-items:center;gap:10px;}',\n"
src += "      '.sp-lbl{font-size:0.62rem;letter-spacing:0.1em;color:var(--subtext,#7070a0);text-transform:uppercase;width:72px;flex-shrink:0;}',\n"
src += "      '.sp-sel{flex:1;background:var(--bg,#0a0a0f);border:1px solid var(--border,#1e1e2e);border-radius:8px;padding:6px 10px;color:var(--text,#e8e8f0);font-family:var(--font-ui,monospace);font-size:0.72rem;outline:none;}',\n"
src += "      '.sp-rng{flex:1;accent-color:#6af7c8;cursor:pointer;}',\n"
src += "      '.sp-val{font-size:0.65rem;color:#6af7c8;width:36px;text-align:right;flex-shrink:0;}',\n"
src += "      '.sp-sw{width:36px;height:28px;border-radius:8px;border:1px solid var(--border,#1e1e2e);cursor:pointer;overflow:hidden;position:relative;}',\n"
src += "      '.sp-sw input{position:absolute;inset:-4px;width:calc(100% + 8px);height:calc(100% + 8px);opacity:0;cursor:pointer;}',\n"
src += "      '.sp-tog{width:36px;height:20px;background:var(--muted,#2a2a3e);border-radius:10px;cursor:pointer;position:relative;transition:background 0.2s;flex-shrink:0;}',\n"
src += "      '.sp-tog.on{background:#6af7c8;}',\n"
src += "      \".sp-tog::after{content:'';position:absolute;top:3px;left:3px;width:14px;height:14px;background:#fff;border-radius:50%;transition:transform 0.2s;}\",\n"
src += "      '.sp-tog.on::after{transform:translateX(16px);}',\n"
src += "      '.sp-tbtn{flex:1;padding:6px 10px;background:var(--bg,#0a0a0f);border:1px solid var(--border,#1e1e2e);border-radius:8px;color:var(--text,#e8e8f0);font-family:var(--font-ui,monospace);font-size:0.72rem;cursor:pointer;transition:all 0.2s;}',\n"
src += "      '.sp-tbtn:hover{border-color:#6af7c8;}',\n"
src += "      '.sp-acts{display:flex;gap:8px;margin-top:2px;}',\n"
src += "      '.sp-abtn{flex:1;padding:8px;background:var(--bg,#0a0a0f);border:1px solid var(--border,#1e1e2e);border-radius:10px;color:var(--subtext,#7070a0);font-family:var(--font-ui,monospace);font-size:0.65rem;cursor:pointer;transition:all 0.2s;}',\n"
src += "      '.sp-abtn:hover{border-color:#6af7c8;color:#6af7c8;}',\n"
src += "    ].join('');\n"
src += "    document.head.appendChild(s);\n"
src += "  }\n"
src += "\n"
src += "  function buildDOM(container){\n"
src += "    container.innerHTML=\n"
src += "      '<div id=\"sp-wrap\">'\n"
src += "      +'<div id=\"sp-presets\">'\n"
src += "      +'<button class=\"sp-preset active\" data-preset=\"sky\">sky</button>'\n"
src += "      +'<button class=\"sp-preset\" data-preset=\"cold\">cold</button>'\n"
src += "      +'<button class=\"sp-preset\" data-preset=\"monday\">monday</button>'\n"
src += "      +'<button class=\"sp-preset\" data-preset=\"grit\">grit</button>'\n"
src += "      +'<button class=\"sp-preset\" data-preset=\"architect\">architect</button>'\n"
src += "      +'<button class=\"sp-preset\" data-preset=\"custom\">custom</button>'\n"
src += "      +'</div>'\n"
src += "      +'<canvas id=\"sp-canvas\"></canvas>'\n"
src += "      +'<div id=\"sp-ctrl\">'\n"
src += "      +'<div class=\"sp-row\"><label class=\"sp-lbl\">type</label><select id=\"sp-type\" class=\"sp-sel\"><option value=\"log\">logarithmic</option><option value=\"archi\">archimedean</option><option value=\"fib\">fibonacci</option><option value=\"galaxy\">galaxy</option></select></div>'\n"
src += "      +'<div class=\"sp-row\"><label class=\"sp-lbl\">color</label><div id=\"sp-cswatch\" class=\"sp-sw\" style=\"background:#00F6D6\"><input type=\"color\" id=\"sp-color\" value=\"#00F6D6\"/></div></div>'\n"
src += "      +'<div class=\"sp-row\"><label class=\"sp-lbl\">speed</label><input type=\"range\" id=\"sp-speed\" min=\"1\" max=\"20\" value=\"6\" class=\"sp-rng\"/><span id=\"sp-spval\" class=\"sp-val\">0.6x</span></div>'\n"
src += "      +'<div class=\"sp-row\"><label class=\"sp-lbl\">density</label><input type=\"range\" id=\"sp-density\" min=\"60\" max=\"400\" value=\"180\" class=\"sp-rng\"/><span id=\"sp-dnval\" class=\"sp-val\">180</span></div>'\n"
src += "      +'<div class=\"sp-row\"><label class=\"sp-lbl\">direction</label><button id=\"sp-dir\" class=\"sp-tbtn\">CW</button></div>'\n"
src += "      +'<div class=\"sp-row\"><label class=\"sp-lbl\">particles</label><div id=\"sp-ptcl\" class=\"sp-tog on\"></div></div>'\n"
src += "      +'<div class=\"sp-row\"><label class=\"sp-lbl\">decay</label><div id=\"sp-decay\" class=\"sp-tog\"></div></div>'\n"
src += "      +'<div class=\"sp-row\"><label class=\"sp-lbl\">screensaver</label><select id=\"sp-idle\" class=\"sp-sel\"><option value=\"2\">after 2 min</option><option value=\"5\" selected>after 5 min</option><option value=\"10\">after 10 min</option><option value=\"0\">off</option></select></div>'\n"
src += "      +'<div class=\"sp-acts\"><button id=\"sp-png\" class=\"sp-abtn\">save PNG</button><button id=\"sp-ssnow\" class=\"sp-abtn\">screensaver now</button></div>'\n"
src += "      +'</div></div>';\n"
src += "\n"
src += "    injectCSS();\n"
src += "    canvas=document.getElementById('sp-canvas');\n"
src += "    ctx=canvas.getContext('2d');\n"
src += "\n"
src += "    document.querySelectorAll('.sp-preset').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));\n"
src += "    q('#sp-type').addEventListener('change',e=>{cfg.type=e.target.value;document.querySelectorAll('.sp-preset').forEach(c=>c.classList.remove('active'));cfg.activePreset='custom';});\n"
src += "    q('#sp-color').addEventListener('input',e=>{cfg.color=e.target.value;q('#sp-cswatch').style.background=e.target.value;});\n"
src += "    q('#sp-speed').addEventListener('input',e=>{cfg.speed=e.target.value/10;q('#sp-spval').textContent=cfg.speed.toFixed(1)+'x';});\n"
src += "    q('#sp-density').addEventListener('input',e=>{cfg.density=parseInt(e.target.value);q('#sp-dnval').textContent=cfg.density;});\n"
src += "    q('#sp-dir').addEventListener('click',()=>{cfg.dir*=-1;q('#sp-dir').textContent=cfg.dir===1?'CW':'CCW';});\n"
src += "    q('#sp-ptcl').addEventListener('click',()=>{cfg.particles=!cfg.particles;q('#sp-ptcl').classList.toggle('on',cfg.particles);if(cfg.particles)initP();});\n"
src += "    q('#sp-decay').addEventListener('click',()=>{cfg.decay=!cfg.decay;q('#sp-decay').classList.toggle('on',cfg.decay);});\n"
src += "    q('#sp-idle').addEventListener('change',e=>{cfg.idleMins=parseInt(e.target.value);resetIdle();});\n"
src += "    q('#sp-png').addEventListener('click',savePNG);\n"
src += "    q('#sp-ssnow').addEventListener('click',enterSS);\n"
src += "    window.addEventListener('resize',setSize);\n"
src += "  }\n"
src += "\n"
src += "  function mount(container){\n"
src += "    if(!container)return;\n"
src += "    buildDOM(container);\n"
src += "    initP();\n"
src += "    applyPreset('sky');\n"
src += "    // Set canvas size after DOM is built using window dims\n"
src += "    setSize();\n"
src += "    stopLoop(); loop();\n"
src += "    ['mousemove','touchstart','keydown','click'].forEach(ev=>document.addEventListener(ev,resetIdle,{passive:true}));\n"
src += "    resetIdle();\n"
src += "  }\n"
src += "  function unmount(){stopLoop();clearTimeout(idleTimer);if(ssActive)exitSS();}\n"
src += "\n"
src += "  return { mount, unmount, applyPreset, savePNG };\n"
src += "})();\n"
src += "\n"
src += "export function initSpiral(){\n"
src += "  const container=document.getElementById('view-spiral');\n"
src += "  if(!container)return;\n"
src += "  SpiralView.mount(container);\n"
src += "}\n"

with open('js/app/views/spiral.js','w',encoding='utf-8') as f:
    f.write(src)
print('wrote spiral.js (' + str(len(src)) + ' chars)')
